import enum

from six.moves import UserDict


class LocaleLanguage(enum.Enum):
    EN = "en"
    JA = "ja"
    DE = ("de",)
    FR = ("fr",)
    KO = "ko"
    ZHS = "zhs"
    ZHT = "zht"
    IT = "it"
    ES = "es"
    NL = "nl"
    SV = "sv"
    PL = "pl"
    FI = "fi"
    DA = "da"
    NO = "no"


class LocaleCurrency(enum.Enum):
    USD = "USD"
    CAD = "CAD"
    JPY = "JPY"
    GBP = "GBP"
    EUR = "EUR"
    HKD = "HKD"
    SGD = "SGD"
    TWD = "TWD"
    KRW = "KRW"
    AUD = "AUD"
    NZD = "NZD"
    INR = "INR"
    DKK = "DKK"
    NOK = "NOK"
    SEK = "SEK"
    ILS = "ILS"
    CNY = "CNY"
    PLN = "PLN"
    CHF = "CHF"
    CZK = "CZK"
    HUF = "HUF"
    RON = "RON"
    ZAR = "ZAR"
    MYR = "MYR"
    THB = "THB"
    PHP = "PHP"


class LocaleSite(enum.Enum):
    US = "US"
    CA = "CA"
    JP = "JP"
    UK = "UK"
    DE = "DE"
    AT = "AT"
    BE = "BE"
    DK = "DK"
    FI = "FI"
    GR = "GR"
    IE = "IE"
    IT = "IT"
    LU = "LU"
    NL = "NL"
    NO = "NO"
    PT = "PT"
    ES = "ES"
    KR = "KR"
    HK = "HK"
    SG = "SG"
    CN = "CN"
    TW = "TW"
    AU = "AU"
    FR = "FR"
    IN = "IN"
    NZ = "NZ"
    SE = "SE"
    MX = "MX"
    CH = "CH"
    IL = "IL"
    PL = "PL"
    SK = "SK"
    SI = "SI"
    LV = "LV"
    LT = "LT"
    EE = "EE"
    CZ = "CZ"
    HU = "HU"
    BG = "BG"
    MY = "MY"
    ZA = "ZA"
    RO = "RO"
    TH = "TH"
    PH = "PH"
    BR = "BR"
    VN = "VN"
